# Generated by Django 5.1.7 on 2025-04-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailhistory',
            name='attachment_name',
        ),
        migrations.AddField(
            model_name='emailhistory',
            name='attachment_names',
            field=models.TextField(blank=True),
        ),
    ]
