# Generated by Django 5.1.2 on 2025-04-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailer', '0002_remove_emailhistory_attachment_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailhistory',
            name='bcc',
            field=models.TextField(blank=True),
        ),
    ]
